const GeoLayout castle_grounds_area_2_myLevel[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 3163, 0, -3725, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, -2073, 0, castle_grounds_Cube_001_mesh),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout castle_grounds_area_2_level[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0xE6BF),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(1, 3163, 0, -3725, 3163, -213, -3725, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, castle_grounds_area_2_myLevel),
					GEO_RENDER_OBJ(),
					GEO_ASM(0, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, castle_grounds_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, castle_grounds_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, castle_grounds_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, castle_grounds_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, castle_grounds_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, castle_grounds_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, castle_grounds_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, castle_grounds_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
