const GeoLayout ccm_area_1_myLevel[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, ccm_Cube_mesh),
				GEO_ANIMATED_PART(1, 1644, 421, 2526, ccm_Icosphere_004_mesh),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ccm_area_1_level[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x8FFD),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(1, 0, 0, 0, 0, -213, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ccm_area_1_myLevel),
					GEO_RENDER_OBJ(),
					GEO_ASM(0, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, ccm_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, ccm_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, ccm_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, ccm_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, ccm_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, ccm_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, ccm_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, ccm_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
