const GeoLayout mower_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, mower_Cube_mesh),
		GEO_DISPLAY_LIST(0, mower_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, mower_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, mower_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, mower_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, mower_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, mower_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, mower_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, mower_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
