const GeoLayout ddd_area_1_myLevel[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(1, 0, 0, 0, NULL),
			GEO_OPEN_NODE(),
				GEO_ANIMATED_PART(1, 0, 0, 0, ddd_Cube_mesh),
				GEO_ANIMATED_PART(1, -176, 1292, 3168, ddd_Cylinder_mesh),
				GEO_ANIMATED_PART(1, -2743, 1292, 3168, ddd_Cylinder_001_mesh),
				GEO_ANIMATED_PART(1, -2743, 1292, 1891, ddd_Cylinder_002_mesh),
				GEO_ANIMATED_PART(1, -176, 1292, 1859, ddd_Cylinder_003_mesh),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout ddd_area_1_level[] = {
	GEO_NODE_SCREEN_AREA(10, SCREEN_WIDTH/2, SCREEN_HEIGHT/2, SCREEN_WIDTH/2, SCREEN_HEIGHT/2),
	GEO_OPEN_NODE(),
		GEO_ZBUFFER(0),
		GEO_OPEN_NODE(),
			GEO_NODE_ORTHO(100.0000),
			GEO_OPEN_NODE(),
				GEO_BACKGROUND_COLOR(0x7C3B),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_ZBUFFER(1),
		GEO_OPEN_NODE(),
			GEO_CAMERA_FRUSTUM_WITH_FUNC(45.0000, 100, 30000, geo_camera_fov),
			GEO_OPEN_NODE(),
				GEO_CAMERA(1, 0, 0, 0, 0, -213, 0, geo_camera_main),
				GEO_OPEN_NODE(),
					GEO_BRANCH(1, ddd_area_1_myLevel),
					GEO_RENDER_OBJ(),
					GEO_ASM(0, geo_envfx_main),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(0, ddd_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, ddd_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, ddd_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, ddd_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, ddd_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, ddd_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, ddd_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, ddd_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
