const GeoLayout rake_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, rake_Cylinder_mesh),
		GEO_DISPLAY_LIST(0, rake_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, rake_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, rake_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, rake_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, rake_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, rake_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, rake_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, rake_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
