const GeoLayout myCamera_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(1, 0, 0, 0, myCamera_Cube_mesh),
		GEO_DISPLAY_LIST(0, myCamera_material_revert_render_settings),
		GEO_DISPLAY_LIST(1, myCamera_material_revert_render_settings),
		GEO_DISPLAY_LIST(2, myCamera_material_revert_render_settings),
		GEO_DISPLAY_LIST(3, myCamera_material_revert_render_settings),
		GEO_DISPLAY_LIST(4, myCamera_material_revert_render_settings),
		GEO_DISPLAY_LIST(5, myCamera_material_revert_render_settings),
		GEO_DISPLAY_LIST(6, myCamera_material_revert_render_settings),
		GEO_DISPLAY_LIST(7, myCamera_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
